### ISSUE TITLE
Add support for launching via Quickstart ID

### ISSUE THREAD

**Issue by ryanj** [ryanj/launch-service#24]
Inbound URLs should look like this:

    http://launch-shifter.rhcloud.com/?quickstart_id=#{id}

**Comment by ryanj** [comment]
@luciddreamz support for quickstart_ids added with this change. Feel free to test and send feedback

http://launch-shifter.rhcloud.com/?quickstart_id=128

**Comment by ryanj** [comment]
I've seen a few errors while hitting these urls: https://hub.openshift.com/quickstarts/deploy/128

Are you able to get the same tracking visibility if I send folks here instead?: https://openshift.redhat.com/app/console/application_type/quickstart!128

The 2nd URL seems more stable

**Comment by luciddreamz** [comment]
We lose tracking visibility (within Hub reporting) with the second URL. Stick with the first one.

Looking into New Relic now to figure out why the errors are occurring. We'll get that fixed ASAP.

**Comment by ryanj** [comment]
@luciddreamz ok, I'll stick with the current URL target.  Let me know if you want any other changes here.
